### PR TITLE
Fix play/pause starting a different track.

### PR DESCRIPTION
**Pull request by plampila**

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Thanks for the PR. Can I please ask under which use-case this happens?

**Comment by plampila** [comment]
At least when using the new look and an artist or album page is open. Didn't try to reproduce in other cases. Each track on the page has a play button that might be chosen instead of the player button for play/pause.

**Comment by julianxhokaxhiu** [comment]
This is actually that the issue #7 I wasn't able to reproduce. Thanks!

**Comment by julianxhokaxhiu** [comment]
Version 1.0.1 has been published.

**Pull request merged**
